-- All lines below this one were originally generated by an llm. The aim of this file is to serve as a decently complete test of this lexer

-- Single-line comment: Testing the bounds of Lua's lexer
--[[ 
  Multi-line comment block.
  We will cover all 22 keywords, various number formats, 
  string boundaries, and Lua 5.3+ operators.
]]

local function extreme_lexer_test(param1, ...)
    ::start_label::

    local int_val    = 42
    local float_val  = 3.14159265
    local sci_val    = 1.2e-5
    local hex_val    = 0xDEADBEEF
    local hex_float  = 0x1.921fb54442d18p+1

    local str_double_empty = ""
    local str_single_empty = ''
    local str_double = "Basic escapes: bell\a, backspace\b, formfeed\f, newline\n, return\r, tab\t, vtab\v, slash\\\\, d-quote\""    
    local str_single = 'Advanced escapes: s-quote\', dec\065, hex\x42, unicode\u{1F445}, and gap\z
                        skipping across newlines.'
    local long_str   = [==[
        Long strings ignore escape sequences like \n.
        The [==[ syntax allows nested [[ ]] blocks inside safely.
    ]==]

    local is_true  = true
    local is_false = false
    local nothing  = nil

    local complex_table = {
        ["key_string"] = str_double .. str_single,
                   ={ ... },
        nested         = int_val+ float_val * 2 / 1
    }

    local tbl_len    = #complex_table
    local power_mod  = (5 ^ 2) % 4
    local floor_div  = 10 // 3
    local bitwise    = (hex_val & 0xFF) | (1 << 4) ~ (int_val >> 1)

    if not is_false and (int_val ~= float_val) then
        ;
    elseif int_val == 42 or nothing == nil then
        local dummy = float_val >= sci_val
    else
        goto start_label
    end

    for i = 1, 10, 2 do
        if i > 5 then break end
    end

    for k, v in pairs(complex_table) do

    end

    local counter = 0
    while counter <= 5 do
        counter = counter + 1
    end

    repeat
        counter = counter - 1
    until counter < 0

    complex_table:dummy_method()

    return function() return tbl_len end
end